[2024-09-27T10:43:00.331+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T10:43:00.350+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.clear_data manual__2024-09-27T10:42:54.520817+00:00 [queued]>
[2024-09-27T10:43:00.367+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.clear_data manual__2024-09-27T10:42:54.520817+00:00 [queued]>
[2024-09-27T10:43:00.368+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-27T10:43:00.386+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): clear_data> on 2024-09-27 10:42:54.520817+00:00
[2024-09-27T10:43:00.394+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=156) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T10:43:00.396+0000] {standard_task_runner.py:72} INFO - Started process 157 to run task
[2024-09-27T10:43:00.396+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'clear_data', 'manual__2024-09-27T10:42:54.520817+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpoiid5mw6']
[2024-09-27T10:43:00.398+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask clear_data
[2024-09-27T10:43:00.444+0000] {task_command.py:467} INFO - Running <TaskInstance: sparking_flow.clear_data manual__2024-09-27T10:42:54.520817+00:00 [running]> on host afb1a6b3c1a2
[2024-09-27T10:43:00.522+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='clear_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T10:42:54.520817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T10:42:54.520817+00:00'
[2024-09-27T10:43:00.523+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T10:43:00.545+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2024-09-27T10:43:00.547+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py
[2024-09-27T10:43:00.631+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-09-27T10:43:08.086+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO SparkContext: Running Spark version 3.5.2
[2024-09-27T10:43:08.102+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-27T10:43:08.103+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO SparkContext: Java version 11
[2024-09-27T10:43:08.383+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-27T10:43:08.814+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO ResourceUtils: ==============================================================
[2024-09-27T10:43:08.820+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-27T10:43:08.822+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO ResourceUtils: ==============================================================
[2024-09-27T10:43:08.823+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO SparkContext: Submitted application: My App
[2024-09-27T10:43:08.912+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-27T10:43:08.984+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO ResourceProfile: Limiting resource is cpu
[2024-09-27T10:43:08.986+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:08 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-27T10:43:09.198+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:09 INFO SecurityManager: Changing view acls to: ***
[2024-09-27T10:43:09.202+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:09 INFO SecurityManager: Changing modify acls to: ***
[2024-09-27T10:43:09.203+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:09 INFO SecurityManager: Changing view acls groups to:
[2024-09-27T10:43:09.205+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:09 INFO SecurityManager: Changing modify acls groups to:
[2024-09-27T10:43:09.206+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:09 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-09-27T10:43:11.151+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:11 INFO Utils: Successfully started service 'sparkDriver' on port 36869.
[2024-09-27T10:43:11.940+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:11 INFO SparkEnv: Registering MapOutputTracker
[2024-09-27T10:43:12.179+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:12 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-27T10:43:12.258+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:12 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-27T10:43:12.261+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:12 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-27T10:43:12.308+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:12 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-27T10:43:12.597+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:12 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-5403189e-0276-40e6-bcdd-a3341a0596c3
[2024-09-27T10:43:13.370+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-27T10:43:14.789+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:14 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-27T10:43:42.806+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-27T10:43:45.636+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-09-27T10:43:50.318+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:50 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-09-27T10:43:50.668+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:50 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-09-27T10:43:50.813+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:50 INFO SparkContext: Added JAR /opt/***/lib/postgresql-42.7.4.jar at spark://afb1a6b3c1a2:36869/jars/postgresql-42.7.4.jar with timestamp 1727433787954
[2024-09-27T10:43:50.936+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:50 ERROR SparkContext: Error initializing SparkContext.
[2024-09-27T10:43:50.938+0000] {spark_submit.py:579} INFO - org.apache.spark.SparkException: Could not parse Master URL: 'spark-master:7077'
[2024-09-27T10:43:50.939+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:3194)
[2024-09-27T10:43:50.940+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:577)
[2024-09-27T10:43:50.942+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-09-27T10:43:50.943+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-09-27T10:43:50.944+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-09-27T10:43:50.945+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-09-27T10:43:50.946+0000] {spark_submit.py:579} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-09-27T10:43:50.949+0000] {spark_submit.py:579} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-09-27T10:43:50.951+0000] {spark_submit.py:579} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-09-27T10:43:50.953+0000] {spark_submit.py:579} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2024-09-27T10:43:50.954+0000] {spark_submit.py:579} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-09-27T10:43:50.954+0000] {spark_submit.py:579} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-09-27T10:43:50.955+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-09-27T10:43:50.956+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-09-27T10:43:50.957+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:834)
[2024-09-27T10:43:50.958+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:50 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-09-27T10:43:50.996+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:50 INFO SparkUI: Stopped Spark web UI at http://afb1a6b3c1a2:4040
[2024-09-27T10:43:51.079+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-09-27T10:43:51.241+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO MemoryStore: MemoryStore cleared
[2024-09-27T10:43:51.243+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO BlockManager: BlockManager stopped
[2024-09-27T10:43:51.290+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-09-27T10:43:51.292+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 WARN MetricsSystem: Stopping a MetricsSystem that is not running
[2024-09-27T10:43:51.307+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-09-27T10:43:51.387+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO SparkContext: Successfully stopped SparkContext
[2024-09-27T10:43:51.393+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-09-27T10:43:51.394+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/clear_data.py", line 61, in <module>
[2024-09-27T10:43:51.396+0000] {spark_submit.py:579} INFO - clear_data()
[2024-09-27T10:43:51.398+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/clear_data.py", line 36, in clear_data
[2024-09-27T10:43:51.401+0000] {spark_submit.py:579} INFO - spark = SparkSession.builder.appName("My App").config("spark.driver.extraClassPath", "/opt/***/lib/postgresql-42.7.4.jar").config("spark.executor.extraClassPath", "/opt/***/lib/postgresql-42.7.4.jar").config("spark.jars", "/opt/***/lib/postgresql-42.7.4.jar").getOrCreate()
[2024-09-27T10:43:51.403+0000] {spark_submit.py:579} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-27T10:43:51.404+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 497, in getOrCreate
[2024-09-27T10:43:51.413+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 515, in getOrCreate
[2024-09-27T10:43:51.424+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 203, in __init__
[2024-09-27T10:43:51.426+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 296, in _do_init
[2024-09-27T10:43:51.427+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 421, in _initialize_context
[2024-09-27T10:43:51.429+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
[2024-09-27T10:43:51.430+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-09-27T10:43:51.431+0000] {spark_submit.py:579} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2024-09-27T10:43:51.432+0000] {spark_submit.py:579} INFO - : org.apache.spark.SparkException: Could not parse Master URL: 'spark-master:7077'
[2024-09-27T10:43:51.434+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:3194)
[2024-09-27T10:43:51.435+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:577)
[2024-09-27T10:43:51.437+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-09-27T10:43:51.438+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-09-27T10:43:51.439+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-09-27T10:43:51.440+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-09-27T10:43:51.441+0000] {spark_submit.py:579} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-09-27T10:43:51.442+0000] {spark_submit.py:579} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-09-27T10:43:51.443+0000] {spark_submit.py:579} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-09-27T10:43:51.444+0000] {spark_submit.py:579} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2024-09-27T10:43:51.445+0000] {spark_submit.py:579} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-09-27T10:43:51.446+0000] {spark_submit.py:579} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-09-27T10:43:51.449+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-09-27T10:43:51.453+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-09-27T10:43:51.455+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:834)
[2024-09-27T10:43:51.456+0000] {spark_submit.py:579} INFO - 
[2024-09-27T10:43:51.636+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO ShutdownHookManager: Shutdown hook called
[2024-09-27T10:43:51.638+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-422034ef-e899-46f6-8cf8-d12fc50001d1
[2024-09-27T10:43:51.683+0000] {spark_submit.py:579} INFO - 24/09/27 10:43:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-a46d4162-3cf4-44e3-ab86-a459887626db
[2024-09-27T10:43:51.911+0000] {job.py:229} INFO - Heartbeat recovered after 46.40 seconds
[2024-09-27T10:43:51.897+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py. Error code is: 1.
[2024-09-27T10:43:51.930+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=clear_data, run_id=manual__2024-09-27T10:42:54.520817+00:00, execution_date=20240927T104254, start_date=20240927T104300, end_date=20240927T104351
[2024-09-27T10:43:51.965+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T10:43:51.967+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task clear_data (Cannot execute: spark-submit --master spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py. Error code is: 1.; 157)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py. Error code is: 1.
[2024-09-27T10:43:52.009+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T10:43:52.146+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T10:43:52.192+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
