[2024-09-27T16:40:51.954+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T16:40:51.979+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.clear_data manual__2024-09-27T16:35:10.021676+00:00 [queued]>
[2024-09-27T16:40:52.000+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.clear_data manual__2024-09-27T16:35:10.021676+00:00 [queued]>
[2024-09-27T16:40:52.002+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-27T16:40:52.037+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): clear_data> on 2024-09-27 16:35:10.021676+00:00
[2024-09-27T16:40:52.044+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=60) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T16:40:52.046+0000] {standard_task_runner.py:72} INFO - Started process 61 to run task
[2024-09-27T16:40:52.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'clear_data', 'manual__2024-09-27T16:35:10.021676+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpr_lyni4w']
[2024-09-27T16:40:52.047+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask clear_data
[2024-09-27T16:40:52.108+0000] {task_command.py:467} INFO - Running <TaskInstance: sparking_flow.clear_data manual__2024-09-27T16:35:10.021676+00:00 [running]> on host 15db728b339c
[2024-09-27T16:40:52.208+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='clear_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T16:35:10.021676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T16:35:10.021676+00:00'
[2024-09-27T16:40:52.209+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T16:40:52.240+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2024-09-27T16:40:52.242+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py
[2024-09-27T16:40:52.310+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-09-27T16:41:04.117+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:04 INFO SparkContext: Running Spark version 3.5.2
[2024-09-27T16:41:04.186+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:04 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-27T16:41:04.190+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:04 INFO SparkContext: Java version 11
[2024-09-27T16:41:04.851+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-27T16:41:05.461+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:05 INFO ResourceUtils: ==============================================================
[2024-09-27T16:41:05.463+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:05 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-27T16:41:05.465+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:05 INFO ResourceUtils: ==============================================================
[2024-09-27T16:41:05.467+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:05 INFO SparkContext: Submitted application: My App
[2024-09-27T16:41:05.629+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:05 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-27T16:41:05.706+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:05 INFO ResourceProfile: Limiting resource is cpu
[2024-09-27T16:41:05.713+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:05 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-27T16:41:06.285+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:06 INFO SecurityManager: Changing view acls to: ***
[2024-09-27T16:41:06.288+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:06 INFO SecurityManager: Changing modify acls to: ***
[2024-09-27T16:41:06.290+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:06 INFO SecurityManager: Changing view acls groups to:
[2024-09-27T16:41:06.291+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:06 INFO SecurityManager: Changing modify acls groups to:
[2024-09-27T16:41:06.295+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-09-27T16:41:07.584+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:07 INFO Utils: Successfully started service 'sparkDriver' on port 43701.
[2024-09-27T16:41:07.776+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:07 INFO SparkEnv: Registering MapOutputTracker
[2024-09-27T16:41:08.315+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:08 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-27T16:41:08.474+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:08 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-27T16:41:08.478+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:08 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-27T16:41:08.495+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:08 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-27T16:41:08.645+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:08 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-55a91151-76de-4deb-ad77-be24c351d7e5
[2024-09-27T16:41:08.742+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:08 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-27T16:41:08.815+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:08 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-27T16:41:09.736+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:09 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-09-27T16:41:09.920+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:09 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-09-27T16:41:10.099+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:10 INFO SparkContext: Added JAR /opt/***/lib/postgresql-42.7.4.jar at spark://15db728b339c:43701/jars/postgresql-42.7.4.jar with timestamp 1727455263833
[2024-09-27T16:41:10.422+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:10 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-09-27T16:41:11.080+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:11 INFO TransportClientFactory: Successfully created connection to spark-master/172.20.0.4:7077 after 504 ms (0 ms spent in bootstraps)
[2024-09-27T16:41:14.247+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240927164113-0000
[2024-09-27T16:41:14.288+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37725.
[2024-09-27T16:41:14.293+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO NettyBlockTransferService: Server created on 15db728b339c:37725
[2024-09-27T16:41:14.296+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-09-27T16:41:14.334+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 15db728b339c, 37725, None)
[2024-09-27T16:41:14.350+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO BlockManagerMasterEndpoint: Registering block manager 15db728b339c:37725 with 434.4 MiB RAM, BlockManagerId(driver, 15db728b339c, 37725, None)
[2024-09-27T16:41:14.360+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 15db728b339c, 37725, None)
[2024-09-27T16:41:14.364+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 15db728b339c, 37725, None)
[2024-09-27T16:41:14.461+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240927164113-0000/0 on worker-20240927163947-172.20.0.8-38845 (172.20.0.8:38845) with 2 core(s)
[2024-09-27T16:41:14.464+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:14 INFO StandaloneSchedulerBackend: Granted executor ID app-20240927164113-0000/0 on hostPort 172.20.0.8:38845 with 2 core(s), 1024.0 MiB RAM
[2024-09-27T16:41:15.800+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:15 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-09-27T16:41:18.065+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:18 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-09-27T16:41:18.186+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:18 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2024-09-27T16:41:48.617+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-27T16:41:48.894+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-09-27T16:41:50.923+0000] {spark_submit.py:579} INFO - 24/09/27 16:41:50 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240927164113-0000/0 is now RUNNING
[2024-09-27T16:42:05.421+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-09-27T16:42:05.444+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/clear_data.py", line 61, in <module>
[2024-09-27T16:42:05.453+0000] {spark_submit.py:579} INFO - clear_data()
[2024-09-27T16:42:05.453+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/clear_data.py", line 55, in clear_data
[2024-09-27T16:42:05.454+0000] {spark_submit.py:579} INFO - sales_df = spark.read.format("jdbc").options(**options).load()
[2024-09-27T16:42:05.455+0000] {spark_submit.py:579} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-27T16:42:05.456+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
[2024-09-27T16:42:05.483+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-09-27T16:42:05.485+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-09-27T16:42:05.487+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-09-27T16:42:05.512+0000] {spark_submit.py:579} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o36.load.
[2024-09-27T16:42:05.513+0000] {spark_submit.py:579} INFO - : java.lang.ClassNotFoundException: org.postgresql.Driver
[2024-09-27T16:42:05.514+0000] {spark_submit.py:579} INFO - at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[2024-09-27T16:42:05.515+0000] {spark_submit.py:579} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[2024-09-27T16:42:05.517+0000] {spark_submit.py:579} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[2024-09-27T16:42:05.518+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:46)
[2024-09-27T16:42:05.519+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1(JDBCOptions.scala:103)
[2024-09-27T16:42:05.521+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$1$adapted(JDBCOptions.scala:103)
[2024-09-27T16:42:05.522+0000] {spark_submit.py:579} INFO - at scala.Option.foreach(Option.scala:407)
[2024-09-27T16:42:05.524+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:103)
[2024-09-27T16:42:05.525+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:41)
[2024-09-27T16:42:05.527+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
[2024-09-27T16:42:05.529+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
[2024-09-27T16:42:05.530+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2024-09-27T16:42:05.531+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2024-09-27T16:42:05.533+0000] {spark_submit.py:579} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-09-27T16:42:05.536+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2024-09-27T16:42:05.539+0000] {spark_submit.py:579} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2024-09-27T16:42:05.540+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-09-27T16:42:05.541+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-09-27T16:42:05.542+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-09-27T16:42:05.545+0000] {spark_submit.py:579} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-09-27T16:42:05.547+0000] {spark_submit.py:579} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-09-27T16:42:05.549+0000] {spark_submit.py:579} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-09-27T16:42:05.550+0000] {spark_submit.py:579} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-09-27T16:42:05.551+0000] {spark_submit.py:579} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-09-27T16:42:05.553+0000] {spark_submit.py:579} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-09-27T16:42:05.553+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-09-27T16:42:05.555+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-09-27T16:42:05.556+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:834)
[2024-09-27T16:42:05.558+0000] {spark_submit.py:579} INFO - 
[2024-09-27T16:42:06.214+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO SparkContext: Invoking stop() from shutdown hook
[2024-09-27T16:42:06.223+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-09-27T16:42:06.287+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO SparkUI: Stopped Spark web UI at http://15db728b339c:4040
[2024-09-27T16:42:06.318+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-09-27T16:42:06.347+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-09-27T16:42:06.436+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-09-27T16:42:06.902+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO MemoryStore: MemoryStore cleared
[2024-09-27T16:42:06.926+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO BlockManager: BlockManager stopped
[2024-09-27T16:42:06.988+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:06 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-09-27T16:42:07.009+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:07 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-09-27T16:42:07.035+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:07 INFO SparkContext: Successfully stopped SparkContext
[2024-09-27T16:42:07.037+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:07 INFO ShutdownHookManager: Shutdown hook called
[2024-09-27T16:42:07.038+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-180b76f5-1de8-40f1-beed-8338da3d5c85
[2024-09-27T16:42:07.065+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-662725e1-a56a-4fd7-ad5a-aabadc5ab215
[2024-09-27T16:42:07.086+0000] {spark_submit.py:579} INFO - 24/09/27 16:42:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-180b76f5-1de8-40f1-beed-8338da3d5c85/pyspark-bb30028d-2485-4ebe-85f7-92bb15af3941
[2024-09-27T16:42:07.859+0000] {job.py:229} INFO - Heartbeat recovered after 55.52 seconds
[2024-09-27T16:42:07.840+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py. Error code is: 1.
[2024-09-27T16:42:07.903+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=clear_data, run_id=manual__2024-09-27T16:35:10.021676+00:00, execution_date=20240927T163510, start_date=20240927T164051, end_date=20240927T164207
[2024-09-27T16:42:08.035+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T16:42:08.037+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 131 for task clear_data (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py. Error code is: 1.; 61)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py. Error code is: 1.
[2024-09-27T16:42:08.129+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T16:42:08.270+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T16:42:08.295+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
