[2024-09-27T10:47:38.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T10:47:38.393+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.clear_data manual__2024-09-27T10:47:32.711891+00:00 [queued]>
[2024-09-27T10:47:38.403+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.clear_data manual__2024-09-27T10:47:32.711891+00:00 [queued]>
[2024-09-27T10:47:38.404+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-27T10:47:38.420+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): clear_data> on 2024-09-27 10:47:32.711891+00:00
[2024-09-27T10:47:38.426+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=311) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T10:47:38.428+0000] {standard_task_runner.py:72} INFO - Started process 312 to run task
[2024-09-27T10:47:38.428+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'clear_data', 'manual__2024-09-27T10:47:32.711891+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmp6v990_rf']
[2024-09-27T10:47:38.430+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask clear_data
[2024-09-27T10:47:38.482+0000] {task_command.py:467} INFO - Running <TaskInstance: sparking_flow.clear_data manual__2024-09-27T10:47:32.711891+00:00 [running]> on host afb1a6b3c1a2
[2024-09-27T10:47:38.565+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='clear_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T10:47:32.711891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T10:47:32.711891+00:00'
[2024-09-27T10:47:38.567+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T10:47:38.592+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2024-09-27T10:47:38.595+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --deploy-mode client jobs/python/clear_data.py
[2024-09-27T10:47:38.665+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-09-27T10:47:44.848+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:44 INFO SparkContext: Running Spark version 3.5.2
[2024-09-27T10:47:44.855+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:44 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-27T10:47:44.858+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:44 INFO SparkContext: Java version 11
[2024-09-27T10:47:45.001+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-27T10:47:45.268+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO ResourceUtils: ==============================================================
[2024-09-27T10:47:45.270+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-27T10:47:45.271+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO ResourceUtils: ==============================================================
[2024-09-27T10:47:45.272+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO SparkContext: Submitted application: My App
[2024-09-27T10:47:45.329+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-27T10:47:45.358+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO ResourceProfile: Limiting resource is cpu
[2024-09-27T10:47:45.361+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-27T10:47:45.489+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO SecurityManager: Changing view acls to: ***
[2024-09-27T10:47:45.491+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO SecurityManager: Changing modify acls to: ***
[2024-09-27T10:47:45.492+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO SecurityManager: Changing view acls groups to:
[2024-09-27T10:47:45.494+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO SecurityManager: Changing modify acls groups to:
[2024-09-27T10:47:45.495+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:45 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-09-27T10:47:46.309+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO Utils: Successfully started service 'sparkDriver' on port 39363.
[2024-09-27T10:47:46.461+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO SparkEnv: Registering MapOutputTracker
[2024-09-27T10:47:46.577+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-27T10:47:46.642+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-27T10:47:46.644+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-27T10:47:46.667+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-27T10:47:46.766+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-fb4ec203-b398-4f86-9460-d167a6d7a06d
[2024-09-27T10:47:46.898+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:46 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-27T10:47:47.023+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:47 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-27T10:47:47.508+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:47 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-09-27T10:47:47.714+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:47 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-09-27T10:47:47.825+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:47 INFO SparkContext: Added JAR /opt/***/lib/postgresql-42.7.4.jar at spark://afb1a6b3c1a2:39363/jars/postgresql-42.7.4.jar with timestamp 1727434064814
[2024-09-27T10:47:48.138+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:48 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-09-27T10:47:48.605+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:48 INFO TransportClientFactory: Successfully created connection to spark-master/172.20.0.4:7077 after 131 ms (0 ms spent in bootstraps)
[2024-09-27T10:47:50.916+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:50 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240927104750-0000
[2024-09-27T10:47:50.952+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:50 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37499.
[2024-09-27T10:47:50.953+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:50 INFO NettyBlockTransferService: Server created on afb1a6b3c1a2:37499
[2024-09-27T10:47:50.959+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:50 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-09-27T10:47:50.987+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:50 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, afb1a6b3c1a2, 37499, None)
[2024-09-27T10:47:51.009+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:51 INFO BlockManagerMasterEndpoint: Registering block manager afb1a6b3c1a2:37499 with 434.4 MiB RAM, BlockManagerId(driver, afb1a6b3c1a2, 37499, None)
[2024-09-27T10:47:51.017+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:51 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, afb1a6b3c1a2, 37499, None)
[2024-09-27T10:47:51.020+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:51 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, afb1a6b3c1a2, 37499, None)
[2024-09-27T10:47:51.132+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:51 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240927104750-0000/0 on worker-20240927103900-172.20.0.7-45137 (172.20.0.7:45137) with 2 core(s)
[2024-09-27T10:47:51.137+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:51 INFO StandaloneSchedulerBackend: Granted executor ID app-20240927104750-0000/0 on hostPort 172.20.0.7:45137 with 2 core(s), 1024.0 MiB RAM
[2024-09-27T10:47:51.870+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:51 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-09-27T10:47:53.604+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:53 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-09-27T10:47:53.713+0000] {spark_submit.py:579} INFO - 24/09/27 10:47:53 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2024-09-27T10:48:26.957+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-27T10:48:34.393+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-09-27T10:49:24.535+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
